### PR TITLE
Add code showing how to remove NIRCam wisps 

### PR DESCRIPTION
**Pull request by bsunnquist**
This notebook demonstrates how to scale, subtract, and/or flag the scattered light "wisps" from NIRCam data using new templates provided by the NIRCam team. The `subtract_wisp.py` contains the code, and the notebook shows how to use it and its optional arguments.

### The First Cell

- [x] The title of the notebook in a first-level heading (eg. `<h1>` or `# in markdown`).
- [x] A brief description of the notebook.
- [x] A table of contents in an [ordered list](https://www.markdownguide.org/basic-syntax/#ordered-lists) (`1., 2.,` etc. in Markdown).
- [x] The author(s) and affiliation(s) (if relevant).
- [x] The date first published.
- [x] The date last edited (if relevant).
- [x] A link to the notebook's source(s) (if relevant).

### The Rest of the Cells

- [x] There is only one H1 (`#` in Markdown) used in the notebook.
- [x] The notebook uses other [heading tags](https://www.markdownguide.org/basic-syntax/#headings) in order (meaning it does not skip numbers). 

## Text

- [x] All link text is descriptive. It tells users where they will be taken if they open the link.
- [x] All acronyms are defined at least the first time they are used. 
- [x] Field-specific/specialized terms are used when needed, but not excessively.

## Code

- [x] Code sections are introduced and explained before they appear in the notebook. This can be fulfilled with a heading in a prior Markdown cell, a sentence preceding it, or a code comment in the code section.
- [x] Code has explanatory comments (if relevant). This is most important for long sections of code.
- [x] If the author has control over the syntax highlighting theme in the notebook, that theme has enough color contrast to be legible.
- [x] Code and code explanations focus on one task at a time. Unless comparison is the point of the notebook, only one method for completing the task is described at a time.

### Images

- [ ] All images (jpg, png, svgs) have an [image description](https://www.w3.org/WAI/tutorials/images/decision-tree/). This could be
    - [ ] [Alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt) (an `alt` property) 
    - [ ] [Empty alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images) for decorative images/images meant to be skipped (an `alt` attribute with no value)
    - [ ] Captions
    - [ ] If no other options will work, the image is decribed in surrounding paragraphs.

- [ ] Any [text present in images](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html) exists in a text form outside of the image (this can be alt text, captions, or surrounding text.)

### Visualizations

- [x] All visualizations have an image description. Review the previous section, Images, for more information on how to add it.
- [ ] [Visualization descriptions](http://diagramcenter.org/specific-guidelines-e.html) include
    - [ ] The type of visualization (like bar chart, scatter plot, etc.)
    - [ ] Title
    - [ ] Axis labels and range
    - [ ] Key or legend
    - [x] An explanation of the visualization's significance to the notebook (like the trend, an outlier in the data, what the author learned from it, etc.)

- [ ] All visualizations and their parts have [enough color contrast](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) ([color contrast checker](https://webaim.org/resources/contrastchecker/)) to be legible. Remember that transparent colors have lower contrast than their opaque versions.
- [ ] All visualizations [convey information with more visual cues than color coding](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html). Use text labels, patterns, or icons alongside color to achieve this.
- [ ] All visualizations have an additional way for notebook readers to access the information. Linking to the original data, including a table of the data in the same notebook, or sonifying the plot are all options.

### CODE REVIEW

**Comment by camipacifici** [comment]
Hi @bsunnquist, thank you for the notebook! Is this ready for technical review?

**Comment by bsunnquist** [comment]
Hi @camipacifici - yes, I think it's ready - thanks! 

The only thing I wasn't sure on is the downloading of the wisp templates. We store them on Box, so I just provide a link for users to download them manually before running the notebook. I tried downloading them programmatically from Box but wasn't able to get it working, but let me know if that's preferred.

**Comment by bsunnquist** [comment]
Sounds good thanks! And I've just tested it by myself, i.e. running on NIRCam data to make sure it works as expected.

**Comment by bhilbert4** [comment]
I just reviewed the notebook, and it looks good to me. The only question I have @bsunnquist: is it possible for a user to turn on the scaling when they supply their own wisp template? 
e.g. results = subtract_wisp('jw01063006004_02101_00005_nrcb4_cal.fits', wisp_data, scale_wisp=True, show_plot=True)
If so, it may be worth mentioning that explicitly.

**Comment by bsunnquist** [comment]
@bhilbert4 Yes that's possible; I've added some clarification on that to the custom templates section.

**Comment by camipacifici** [comment]
@bhilbert4 is this ready for technical review?

**Comment by bhilbert4** [comment]
Yes, ready for technical review.

**Comment by rizeladiaz** [comment]
@bsunnquist I forgot to mention that I had also changed the requirements.txt file to point to jwst 1.15.1 but I didn't send you that one. I tested it with that version. 
1) Could you please change the requirements.txt file to use 1.15.1 
2) Could you remove the last cell of the notebook? It adds a new empty cell after running the last cell. Probably we have to add a footer to prevent that from happening whenever there is a revision.

**Comment by bsunnquist** [comment]
@rizeladiaz updated with those changes

**Review by rizeladiaz — APPROVED** [review]

**Review by rizeladiaz — APPROVED** [review]
Ready to merge

**Review by camipacifici — APPROVED** [review]
Good to go.

**Comment by camipacifici** [comment]
Thank you @bsunnquist and @rizeladiaz!

**Pull request merged**
