### PR TITLE
Notebook to make RGB images with Imviz

### PR DESCRIPTION
**Pull request by camipacifici**
@kecnry @duytnguyendtn 
I took the liberty of making your notebook a JDAT notebook with the proper intro and footer.
Let me know if you want any changes.

### CODE REVIEW

**Comment by kecnry** [comment]
thanks for cleaning this up!  My only comment would be that it might be nice to make use of batch loading, so maybe:

```
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    with imviz.batch_load():
        for fn in files:
            imviz.load_data(f'{data_dir}/{fn}', data_label=fn[31:36])
```

but that also gets quite ugly with all the nesting.  Can we move the warnings filter outside or do we want them to be enabled for the rest of the notebook?

**Comment by haticekaratay** [comment]
Hi @camipacifici, you got another response from the review bot. Can you please address the warnings when you get a chance?

**Comment by camipacifici** [comment]
Thank you, @haticekaratay! I'll work on this later today

**Comment by camipacifici** [comment]
I addressed the PEP8 comments and the comment by Kyle.

**Review by haticekaratay — APPROVED** [review]

**Pull request merged**
